apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    ssh:
        allow: true
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 2
    ssh:
        allow: true